# more on this here http://jekyllrb.com/docs/configuration/

timezone: America/Chicago

defaults:
  -
    scope:
      path: ""
#      type: "pages" # posts, drafts,
    values:
      layout: "default"
